# Generated by Django 5.1.6 on 2025-03-02 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_user_order_trader_order_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiredorderlog',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.order'),
        ),
    ]
