# Generated by Django 5.1.6 on 2025-03-02 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options'),
        ('sales', '0003_expiredorderlog_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredorderlog',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.order'),
        ),
        migrations.AlterField(
            model_name='expiredorderlog',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expiredorderlog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expired_orders', to='products.product'),
        ),
        migrations.AlterField(
            model_name='expiredorderlog',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expired_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
